BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Prompts] (
    [id] UNIQUEIDENTIFIER NOT NULL,
    [name] NVARCHAR(100) NOT NULL,
    [type] SMALLINT NOT NULL,
    [content] NVARCHAR(2048) NULL,
    [description] NVARCHAR(100),
    [createUserId] UNIQUEIDENTIFIER NOT NULL,
    [isDeleted] BIT NOT NULL CONSTRAINT [Prompts_isDeleted_df] DEFAULT 0,
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Prompts_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [updatedAt] DATETIME2 NOT NULL,
    CONSTRAINT [Prompts_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- AddForeignKey
ALTER TABLE [dbo].[Prompts] ADD CONSTRAINT [Prompts_createUserId_fkey] FOREIGN KEY ([createUserId]) REFERENCES [dbo].[Users]([id]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
