BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[ChatMessages] ADD [inputTokens] INT NOT NULL CONSTRAINT [ChatMessages_inputTokens_df] DEFAULT 0,
[outputTokens] INT NOT NULL CONSTRAINT [ChatMessages_outputTokens_df] DEFAULT 0;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
