BEGIN TRY

BEGIN TRAN;

-- DropForeignKey
ALTER TABLE [dbo].[Chats] DROP CONSTRAINT [Chats_chatModelId_fkey];

-- AlterTable
ALTER TABLE [dbo].[Chats] ALTER COLUMN [chatModelId] NVARCHAR(1000) NULL;

-- AddForeignKey
ALTER TABLE [dbo].[Chats] ADD CONSTRAINT [Chats_chatModelId_fkey] FOREIGN KEY ([chatModelId]) REFERENCES [dbo].[ChatModels]([id]) ON DELETE SET NULL ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
